name: hatgame
description: Hat — a word game

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1  # TODO: Sync with git_version.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1

  quiver: ^3.0.1+1

  built_collection: ^5.1.1
  built_value: ^8.1.4

  yaml: ^3.1.0

  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_analytics: ^10.4.1

  shared_preferences: ^2.0.12

  ntp: ^2.0.0

  url_launcher: ^6.0.18

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  unicode: ^0.3.1

  easy_localization: ^3.0.0
  easy_localization_loader: ^2.0.0

  flutter_markdown: ^0.7.3+1
  flutter_expandable_fab: ^2.3.0

  soundpool: ^2.2.0

  vibration: ^1.7.5

dev_dependencies:
  test: ^1.17.12
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  built_value_generator: ^8.1.4

  source_gen: ^1.2.1

  fake_cloud_firestore: ^2.4.1+1

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - lexicon/
    - sounds/
    - translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
