// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7jo-zBfl0EKR6s7-ph4NhifkhIPzvzw',
    appId: '1:761993928349:web:a9f63af19ae7b1c9b87e74',
    messagingSenderId: '761993928349',
    projectId: 'hatgame',
    authDomain: 'hatgame.firebaseapp.com',
    databaseURL: 'https://hatgame.firebaseio.com',
    storageBucket: 'hatgame.appspot.com',
    measurementId: 'G-TNXGM73WRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOSPwZlw-mTJ5tGlG-ufhDPJsQQ2OSbjs',
    appId: '1:761993928349:android:2fa0a618b9c502f2b87e74',
    messagingSenderId: '761993928349',
    projectId: 'hatgame',
    databaseURL: 'https://hatgame.firebaseio.com',
    storageBucket: 'hatgame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0N0uXlDA5m0JIShltfgerUkrwcxlr8xM',
    appId: '1:761993928349:ios:271e496398d4a2d0b87e74',
    messagingSenderId: '761993928349',
    projectId: 'hatgame',
    databaseURL: 'https://hatgame.firebaseio.com',
    storageBucket: 'hatgame.appspot.com',
    iosBundleId: 'com.amatveyakin.hatgame',
  );
}
